name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:

    runs-on: macos-latest
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies
      run: bundle install --without development
    - name: Run tests
      run: bundle exec rake spec
